### ISSUE TITLE
ReadMe issues with Android Setup

### ISSUE THREAD

**Issue by Benmidi** [ldn0x7dc/react-native-media-kit#1]
The path to project is set to your User, here's a dynamic/relative path:
`include ':react-native-media-kit'
project(':react-native-media-kit').projectDir = new File('../node_modules/react-native-media-kit/android')
`

Also, in MainActivity, you need to import the package:
`import com.yoai.reactnative.media.MediaKitPackage;`

I'm having trouble getting videos to play on Android... but I'm still trying to figure that out.

**Comment by ldn0x7dc** [comment]
@Benmidi Thanks! 
The path issue is a big stupid mistake I've made. I'll update the README asap.
And I'll add the import line.

**Comment by ldn0x7dc** [comment]
@Benmidi 
So what's your trouble playing videos on Android? I'm willing to help~

**Comment by Benmidi** [comment]
Thanks. I've hit two issues.

The player/controls etc. show up but it never gets past the loader, here's the url I'm using: http://www.refinery29.com/file/705/glitter-lips-edit.mp4

Also, I haven't figured out how to load local videos on iOS? 
(the remote url above does work on iOS however)

Thanks for the help!

**Comment by ldn0x7dc** [comment]
@Benmidi 
1. I've reproduced the problem using an android 4.1.1 Genymotion emulator. The Android player should have encountered some decode error like `E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)` in the background and we are not handling it yet. The error could be like [this one](https://github.com/google/ExoPlayer/issues/561) since we use [ExoPlayer](https://github.com/google/ExoPlayer). I'll dig into it later.
2. Local videos are not supported yet but we put this function as a top priority in next releases.

Could you please post your android device here?Is it an emulator or a physical device?In my case, the Genymotion emulator does bad in playing videos but a physical device does well.

**Comment by keyurparalkar** [comment]
I am unable to install the package it get stuck at npm
